# Generated by Django 3.2.3 on 2021-05-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSelling',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('dec', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
